package uz.ciasev.ubdd_service.service.court.files;

import org.springframework.stereotype.Component;
import uz.ciasev.ubdd_service.entity.invoice.Invoice;

@Component
public class CourtGeneratedFileUriBuilder {

    public static String DECISION_WEB_URL = "autogenerated/pdf/decision/";
    public static String INVOICE_WEB_URL = "autogenerated/pdf/invoice/";
    public static String PROTOCOL_WEB_URL = "autogenerated/pdf/protocol/";
    public static String PERSON_CARD_WEB_URL = "autogenerated/pdf/person-card/";

    public String getUriForDecision(Long decisionId) {
        return DECISION_WEB_URL + decisionId;
    }

    public String getUriForProtocol(Long protocolId) {
        return PROTOCOL_WEB_URL + protocolId;
    }

    public String getUriForPersonCard(Long id) {
        return PERSON_CARD_WEB_URL + id;
    }

    public String getUriForInvoice(Invoice invoice) {
        return INVOICE_WEB_URL + invoice.getId();
    }
}
