package uz.ciasev.ubdd_service.entity.protocol;

import uz.ciasev.ubdd_service.utils.FioUtils;

public interface ProtocolCourtAutogeneratedPdfProjection {

    Long getId();

    Boolean getIsMain();

    Long getViolatorDetailId();

    String getViolatorFirstNameLat();

    String getViolatorSecondNameLat();

    String getViolatorLastNameLat();

    default String getViolatorFIO() {
        return FioUtils.buildFullFio(
                this.getViolatorFirstNameLat(),
                this.getViolatorSecondNameLat(),
                this.getViolatorLastNameLat());
    }

}
