package uz.ciasev.ubdd_service.entity.dict;

public enum DocumentTypeAlias {
    VIOLATOR_EXPLANATORY,
    VIOLATOR_DISAGREE,
    SCENE_PHOTO,
    VEHICLE_NUMBER_PHOTO,
    ADDRESS_VERIFICATION,
    PROPERTY_FOR_RECOVERY,
    EXECUTION_REQUIREMENT,
    DECISION,
    MIB_NOTIFICATION_MAIL,
    MIB_NOTIFICATION_MANUAL_MAIL,
    POOR_PERSON,
    INSIGNIFICANT,
    PICHAL_TREBOVANIYA,
    PROTOCOl,
    PERSON_CARD,
    MANUAL_315_RESOLUTION,
    OTHER
}
