package uz.ciasev.ubdd_service.entity.resolution.decision;


import uz.ciasev.ubdd_service.utils.FioUtils;

public interface DecisionCourtAutogeneratedPdfProjection {

    Long getId();

    String getViolatorFirstNameLat();

    String getViolatorSecondNameLat();

    String getViolatorLastNameLat();

    default String getViolatorFIO() {
        return FioUtils.buildFullFio(
                this.getViolatorFirstNameLat(),
                this.getViolatorSecondNameLat(),
                this.getViolatorLastNameLat());
    }
}