package uz.ciasev.ubdd_service.entity.signature;

public enum SignatureEvent {

    PROTOCOL_CREATION,
    PROTOCOL_EDIT_QUALIFICATION,
    RESOLUTION,
    RESOLUTION_CANCEL,
    ADM_CASE_DELETE, ADM_CASE_DELETE_REQUEST_APPROVE,
    SEND_TO_COURT,
    PUNISHMENT_MANUAL_EXECUTION,
    VIOLATOR_REBIND,
    VICTIM_DELETE,
    DAMAGE_EDIT,
    DAMAGE_DELETE,
    VIOLATOR_EDIT,
    EVIDENCE_DELETE,
    ADM_CASE_DOCUMENT_DELETE,REQUIREMENT_GENERATION
}
