package uz.ciasev.ubdd_service.repository.settings;

import uz.ciasev.ubdd_service.entity.settings.OrganConsideredArticlePartSettings;


public interface OrganConsideredArticlePartSettingsCustomRepository extends OrganArticlePartSettingsCustomRepository<OrganConsideredArticlePartSettings> {
}
