package uz.ciasev.ubdd_service.entity;

public enum EntityNameAlias {
    PROTOCOL,
    CASE,
    RESOLUTION,
    CANCELLATION_RESOLUTION,
    DECISION,
    COMPENSATION,
    INVOICE,
    PUNISHMENT,
    EVIDENCE_DECISION,
    MAIL_NOTIFICATION,
    MANUAL_NOTIFICATION,
    COURT_CASE_FIELDS,
    COURT_CASE_CHANCELLERY_DATA,
    SMS_NOTIFICATION,
    MIB_EXECUTION_CARD,

    VICTIM, PARTICIPANT, VIOLATOR, EVIDENCE, DOCUMENT, VIOLATOR_DETAIL, VICTIM_DETAIL, PARTICIPANT_DETAIL, DAMAGE,
    LAST_EMPLOYMENT_INFO,

    PUNISHMENT_DOCUMENT,
    MIB_CARD_DOCUMENT,
    MIB_RETURN_REQUEST,

    REQUIREMENT,
    DIGITAl_SIGNATURE,
    PROSECUTOR_PROTEST,
    PROSECUTOR_PROTEST_DOCUMENT,
    MIB_CARD_MOVEMENT_RETURN_REQUEST,
    ADM_CASE_DELETION_REQUEST,
    DAMAGE_SETTLEMENT_DETAIL;

    public static final String DECISION_NAME = "DECISION";
}
