package uz.ciasev.ubdd_service.event;

public enum AdmEventType {

    //ADM
    PROTOCOL_CREATE, //1
    SEND_ADM_CASE_TO_ORGAN,
    RETURN_ADM_CASE_FROM_ORGAN,
    ORGAN_RESOLUTION_CREATE,
    PROTOCOL_CONSIDER,
    DECISIONS_CANCEL,

    //COURT
    ADM_CASE_REGISTRATION_STATUS_IN_COURT,
    COURT_RESOLUTION_CREATE,
    COURT_RETURN_ADM_CASE,
    REGISTERED_MATERIAL_IN_COURT,

    //MIB
    MIB_PRE_SEND,
    MIB_RETURN_DECISION,
    MIB_RESOLUTION_CREATE,


    //STATUS CHANGE
    ADM_CASE_STATUS_CHANGE,
    DECISION_STATUS_CHANGE,
    PUNISHMENT_STATUS_CHANGE,
    COMPENSATION_STATUS_CHANGE,

    // WANTED
    WANTED_PERSON_DETECTED,
}
